<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'miscal5_industrialdelivery');
define('_DB_USER_', 'miscal5_ideliver');
define('_DB_PASSWD_', 'millonaris2');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'sahxyimgspni6tq4zm7w6l2bhievpc1rpus3h7jmholst94fyjcwsslv');
define('_COOKIE_IV_', '0ihytxp2');
define('_PS_CREATION_DATE_', '2014-11-25');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'HnZku5pTGcS6hYILB65G9IW3tBZZ5RFM');
define('_RIJNDAEL_IV_', 'UtxOkhMA3nnXh3QdNIeV+A==');
