<?php
$query = " 
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block` (
  `id_loffc_block` int(11) NOT NULL AUTO_INCREMENT,
  `width` float(10,2) NOT NULL,
  `show_title` tinyint(1) NOT NULL,
  `id_position` tinyint(2) NOT NULL,
  PRIMARY KEY (`id_loffc_block`)
) ENGINE=_MYSQL_ENGINE_  DEFAULT CHARSET=utf8 AUTO_INCREMENT=64 ;

INSERT INTO `_DB_PREFIX_loffc_block` (`id_loffc_block`, `width`, `show_title`, `id_position`) VALUES
 (1, 0.00, 0, 1),
(46, 20.00, 1, 2),
(54, 20.00, 1, 2),
(55, 35.00, 1, 2),
(56, 25.00, 1, 2),
(57, 0.00, 0, 3),
(58, 0.00, 0, 3);



CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_item` (
  `id_loffc_block_item` int(11) NOT NULL AUTO_INCREMENT,
  `id_loffc_block` int(11) NOT NULL,
  `type` varchar(25) NOT NULL,
  `link` varchar(2000) NOT NULL,
  `linktype` varchar(25) NOT NULL,
  `link_content` varchar(2000) NOT NULL,
  `module_name` varchar(100) NOT NULL,
  `hook_name` varchar(100) NOT NULL,
  `latitude` varchar(25) NOT NULL,
  `longitude` varchar(25) NOT NULL,
  `addthis` tinyint(1) NOT NULL,
  `show_title` tinyint(1) NOT NULL DEFAULT '1',
  `target` varchar(20) NOT NULL DEFAULT '_self',
  `position` int(11) NOT NULL,
  PRIMARY KEY (`id_loffc_block_item`)
) ENGINE=_MYSQL_ENGINE_  DEFAULT CHARSET=utf8 AUTO_INCREMENT=105 ;

INSERT INTO `_DB_PREFIX_loffc_block_item` (`id_loffc_block_item`, `id_loffc_block`, `type`, `link`, `linktype`, `link_content`, `module_name`, `hook_name`, `latitude`, `longitude`, `addthis`, `show_title`, `target`, `position`) VALUES
  (5, 1, 'custom_html', '', '', '', '', '', '', '', 0, 0, '', 0),
 (49, 46, 'link', '', 'cms', '4', '', '', '', '', 0, 1, '_self', 0),
 (72, 54, 'link', '', 'category', '3', '', '', '', '', 0, 1, '_blank', 0),
 (73, 54, 'link', '', 'category', '4', '', '', '', '', 0, 1, '_self', 0),
 (74, 54, 'link', '', 'cms', '5', '', '', '', '', 0, 1, '_self', 0),
 (75, 54, 'link', '', 'cms', '1', '', '', '', '', 0, 1, '_self', 0),
 (76, 54, 'link', '', 'cms', '2', '', '', '', '', 0, 1, '_self', 0),
 (77, 55, 'module', '', '', '', 'leotwitter', 'displayfooter', '', '', 0, 0, '', 0),
 (82, 56, 'custom_html', '', '', '', '', '', '', '', 0, 0, '', 0),
 (85, 46, 'link', '', 'cms', '1', '', '', '', '', 0, 1, '_self', 1),
 (86, 46, 'link', '', 'cms', '3', '', '', '', '', 0, 1, '_self', 2),
 (87, 46, 'link', '', 'cms', '2', '', '', '', '', 0, 1, '_self', 3),
 (88, 46, 'link', '', 'cms', '4', '', '', '', '', 0, 1, '_self', 4),
 (89, 46, 'link', '', 'cms', '4', '', '', '', '', 0, 1, '_self', 5),
 (90, 46, 'link', '', 'cms', '1', '', '', '', '', 0, 1, '_self', 6),
 (91, 54, 'link', '', 'cms', '4', '', '', '', '', 0, 1, '_self', 1),
 (92, 54, 'link', '', 'cms', '1', '', '', '', '', 0, 1, '_self', 2),
 (93, 57, 'custom_html', '', '', '', '', '', '', '', 0, 0, '', 0),
 (94, 57, 'link', '', 'link', 'http://www.leotheme.com/', '', '', '', '', 0, 1, '_self', 1),
 (95, 58, 'module', '', '', '', 'blocknewsletter', 'displayfooter', '', '', 0, 0, '', 0);

CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_item_lang` (
  `id_loffc_block_item` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `text` text NOT NULL,
  PRIMARY KEY (`id_loffc_block_item`,`id_lang`)
) ENGINE=_MYSQL_ENGINE_ DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_loffc_block_item_lang` (`id_loffc_block_item`, `id_lang`, `title`, `text`) VALUES
  (0, 1, 'item 1', ''),
 (0, 2, 'item 1', ''),
 (0, 3, 'item 1', ''),
 (0, 4, 'item 1', ''),
 (0, 5, 'item 1', ''),
 (0, 6, 'item 1', ''),
 (5, 1, 'Social Links', '<div class=\"custom-pos1\">\r\n<h2 class=\"shipping\">Free shipping on orders over $100</h2>\r\n<h2 class=\"call\">Call Us! Toll Free</h2>\r\n<span>123-456-789</span>\r\n<ul>\r\n<li class=\"twitter\"><a href=\"#\">Follow UsTwitter</a></li>\r\n<li class=\"rss\"><a href=\"#\">rss</a></li>\r\n<li class=\"facebook\"><a href=\"#\">Facebook</a></li>\r\n<li class=\"skype\"><a href=\"#\">Skype</a></li>\r\n</ul>\r\n</div>'),
 (5, 2, 'item 3', '<div class=\"custom-pos1\">\r\n<h2 class=\"shipping\">Free shipping on orders over $100</h2>\r\n<h2 class=\"call\">Call Us! Toll Free</h2>\r\n<span>123-456-789</span>\r\n<ul>\r\n<li class=\"twitter\"><a href=\"#\">Follow UsTwitter</a></li>\r\n<li class=\"rss\"><a href=\"#\">rss</a></li>\r\n<li class=\"facebook\"><a href=\"#\">Facebook</a></li>\r\n<li class=\"skype\"><a href=\"#\">Skype</a></li>\r\n</ul>\r\n</div>'),
 (5, 3, 'item 3', '<div class=\"custom-pos1\">\r\n<h2 class=\"shipping\">Free shipping on orders over $100</h2>\r\n<h2 class=\"call\">Call Us! Toll Free</h2>\r\n<span>123-456-789</span>\r\n<ul>\r\n<li class=\"twitter\"><a href=\"#\">Follow UsTwitter</a></li>\r\n<li class=\"rss\"><a href=\"#\">rss</a></li>\r\n<li class=\"facebook\"><a href=\"#\">Facebook</a></li>\r\n<li class=\"skype\"><a href=\"#\">Skype</a></li>\r\n</ul>\r\n</div>'),
 (5, 4, 'item 3', '<div class=\"custom-pos1\">\r\n<h2 class=\"shipping\">Free shipping on orders over $100</h2>\r\n<h2 class=\"call\">Call Us! Toll Free</h2>\r\n<span>123-456-789</span>\r\n<ul>\r\n<li class=\"twitter\"><a href=\"#\">Follow UsTwitter</a></li>\r\n<li class=\"rss\"><a href=\"#\">rss</a></li>\r\n<li class=\"facebook\"><a href=\"#\">Facebook</a></li>\r\n<li class=\"skype\"><a href=\"#\">Skype</a></li>\r\n</ul>\r\n</div>'),
 (5, 5, 'item 3', '<div class=\"custom-pos1\">\r\n<h2 class=\"shipping\">Free shipping on orders over $100</h2>\r\n<h2 class=\"call\">Call Us! Toll Free</h2>\r\n<span>123-456-789</span>\r\n<ul>\r\n<li class=\"twitter\"><a href=\"#\">Follow UsTwitter</a></li>\r\n<li class=\"rss\"><a href=\"#\">rss</a></li>\r\n<li class=\"facebook\"><a href=\"#\">Facebook</a></li>\r\n<li class=\"skype\"><a href=\"#\">Skype</a></li>\r\n</ul>\r\n</div>'),
 (5, 6, 'item 3', '<div class=\"custom-pos1\">\r\n<h2 class=\"shipping\">Free shipping on orders over $100</h2>\r\n<h2 class=\"call\">Call Us! Toll Free</h2>\r\n<span>123-456-789</span>\r\n<ul>\r\n<li class=\"twitter\"><a href=\"#\">Follow UsTwitter</a></li>\r\n<li class=\"rss\"><a href=\"#\">rss</a></li>\r\n<li class=\"facebook\"><a href=\"#\">Facebook</a></li>\r\n<li class=\"skype\"><a href=\"#\">Skype</a></li>\r\n</ul>\r\n</div>'),
 (5, 7, 'Social Links', '<div class=\"custom-pos1\">\r\n<h2 class=\"shipping\">Free shipping on orders over $100</h2>\r\n<h2 class=\"call\">Call Us! Toll Free</h2>\r\n<span>123-456-789</span>\r\n<ul>\r\n<li class=\"twitter\"><a href=\"#\">Follow UsTwitter</a></li>\r\n<li class=\"rss\"><a href=\"#\">rss</a></li>\r\n<li class=\"facebook\"><a href=\"#\">Facebook</a></li>\r\n<li class=\"skype\"><a href=\"#\">Skype</a></li>\r\n</ul>\r\n</div>'),
 (49, 1, 'Help & Contact', ''),
 (49, 2, 'About us', ''),
 (49, 3, 'About us', ''),
 (49, 4, 'About us', ''),
 (49, 5, 'About us', ''),
 (49, 6, 'About us', ''),
 (49, 7, 'Help & Contact', ''),
 (72, 1, 'Women', ''),
 (72, 2, 'Terms', ''),
 (72, 3, 'Terms', ''),
 (72, 4, 'Terms', ''),
 (72, 5, 'Terms', ''),
 (72, 6, 'Terms', ''),
 (72, 7, 'Women', ''),
 (73, 1, 'Men', ''),
 (73, 2, 'About us', ''),
 (73, 3, 'About us', ''),
 (73, 4, 'About us', ''),
 (73, 5, 'About us', ''),
 (73, 6, 'About us', ''),
 (73, 7, 'Men', ''),
 (74, 1, 'Buy Gift Vouchures', ''),
 (74, 2, 'Address', ''),
 (74, 3, 'Address', ''),
 (74, 4, 'Address', ''),
 (74, 5, 'Address', ''),
 (74, 6, 'Address', ''),
 (74, 7, 'Buy Gift Vouchures', ''),
 (75, 1, 'Delivery Option', ''),
 (75, 2, 'Privacy Policy', ''),
 (75, 3, 'Privacy Policy', ''),
 (75, 4, 'Privacy Policy', ''),
 (75, 5, 'Privacy Policy', ''),
 (75, 6, 'Privacy Policy', ''),
 (75, 7, 'Delivery Option', ''),
 (76, 1, 'Customs & Import Tax', ''),
 (76, 2, 'Your account', ''),
 (76, 3, 'Your account', ''),
 (76, 4, 'Your account', ''),
 (76, 5, 'Your account', ''),
 (76, 6, 'Your account', ''),
 (76, 7, 'Customs & Import Tax', ''),
 (77, 1, 'Twitter', ''),
 (77, 2, 'Contact', ''),
 (77, 3, 'Contact', ''),
 (77, 4, 'Contact', ''),
 (77, 5, 'Contact', ''),
 (77, 6, 'Contact', ''),
 (77, 7, 'Twitter', ''),
 (82, 1, 'Top seller', '<p><a href=\"#\"><img src=\"themes/leoconv/img/default/icon-payment.png\" alt=\"\" /></a></p>'),
 (82, 2, 'Top seller', '<p><a href=\"#\"><img src=\"themes/leoconv/img/default/icon-payment.png\" alt=\"\" /></a></p>'),
 (82, 3, 'Top seller', '<p><a href=\"#\"><img src=\"themes/leoconv/img/default/icon-payment.png\" alt=\"\" /></a></p>'),
 (82, 4, 'Top seller', '<p><a href=\"#\"><img src=\"themes/leoconv/img/default/icon-payment.png\" alt=\"\" /></a></p>'),
 (82, 5, 'Top seller', '<p><a href=\"#\"><img src=\"themes/leoconv/img/default/icon-payment.png\" alt=\"\" /></a></p>'),
 (82, 6, 'Top seller', '<p><a href=\"#\"><img src=\"themes/leoconv/img/default/icon-payment.png\" alt=\"\" /></a></p>'),
 (82, 7, 'Top seller', '<p><a href=\"#\"><img src=\"themes/leoconv/img/default/icon-payment.png\" alt=\"\" /></a></p>'),
 (85, 1, 'Delivery & Returns', ''),
 (85, 2, 'Delivery & Returns', ''),
 (85, 3, 'Delivery & Returns', ''),
 (85, 4, 'Delivery & Returns', ''),
 (85, 5, 'Delivery & Returns', ''),
 (85, 6, 'Delivery & Returns', ''),
 (85, 7, 'Delivery & Returns', ''),
 (86, 1, 'Track Ordert', ''),
 (86, 2, 'Track Ordert', ''),
 (86, 3, 'Track Ordert', ''),
 (86, 4, 'Track Ordert', ''),
 (86, 5, 'Track Ordert', ''),
 (86, 6, 'Track Ordert', ''),
 (86, 7, 'Track Ordert', ''),
 (87, 1, 'Upcomming Features', ''),
 (87, 2, 'Upcomming Features', ''),
 (87, 3, 'Upcomming Features', ''),
 (87, 4, 'Upcomming Features', ''),
 (87, 5, 'Upcomming Features', ''),
 (87, 6, 'Upcomming Features', ''),
 (87, 7, 'Upcomming Features', ''),
 (88, 1, 'Contact Us', ''),
 (88, 2, 'Contact Us', ''),
 (88, 3, 'Contact Us', ''),
 (88, 4, 'Contact Us', ''),
 (88, 5, 'Contact Us', ''),
 (88, 6, 'Contact Us', ''),
 (88, 7, 'Contact Us', ''),
 (89, 1, 'Help & Contact', ''),
 (89, 2, 'Help & Contact', ''),
 (89, 3, 'Help & Contact', ''),
 (89, 4, 'Help & Contact', ''),
 (89, 5, 'Help & Contact', ''),
 (89, 6, 'Help & Contact', ''),
 (89, 7, 'Help & Contact', ''),
 (90, 1, 'Delivery & Returns', ''),
 (90, 2, 'Delivery & Returns', ''),
 (90, 3, 'Delivery & Returns', ''),
 (90, 4, 'Delivery & Returns', ''),
 (90, 5, 'Delivery & Returns', ''),
 (90, 6, 'Delivery & Returns', ''),
 (90, 7, 'Delivery & Returns', ''),
 (91, 1, 'Help & Contact', ''),
 (91, 2, 'Help & Contact', ''),
 (91, 3, 'Help & Contact', ''),
 (91, 4, 'Help & Contact', ''),
 (91, 5, 'Help & Contact', ''),
 (91, 6, 'Help & Contact', ''),
 (91, 7, 'Help & Contact', ''),
 (92, 1, 'Delivery & Returns', ''),
 (92, 2, 'Delivery & Returns', ''),
 (92, 3, 'Delivery & Returns', ''),
 (92, 4, 'Delivery & Returns', ''),
 (92, 5, 'Delivery & Returns', ''),
 (92, 6, 'Delivery & Returns', ''),
 (92, 7, 'Delivery & Returns', ''),
 (93, 1, 'copyright', '<p>© 2012 All Rights Reserved. Designer by</p>'),
 (93, 2, 'copyright', '<p>© 2012 All Rights Reserved. Designer by</p>'),
 (93, 3, 'copyright', '<p>© 2012 All Rights Reserved. Designer by</p>'),
 (93, 4, 'copyright', '<p>© 2012 All Rights Reserved. Designer by</p>'),
 (93, 5, 'copyright', '<p>© 2012 All Rights Reserved. Designer by</p>'),
 (93, 6, 'copyright', '<p>© 2012 All Rights Reserved. Designer by</p>'),
 (93, 7, 'copyright', '<p>© 2012 All Rights Reserved. Designer by</p>'),
 (94, 1, 'LeoTheme', ''),
 (94, 2, 'LeoTheme', ''),
 (94, 3, 'LeoTheme', ''),
 (94, 4, 'LeoTheme', ''),
 (94, 5, 'LeoTheme', ''),
 (94, 6, 'LeoTheme', ''),
 (94, 7, 'LeoTheme', ''),
 (95, 1, 'search', ''),
 (95, 2, 'search', ''),
 (95, 3, 'search', ''),
 (95, 4, 'search', ''),
 (95, 5, 'search', ''),
 (95, 6, 'search', ''),
 (95, 7, 'search', '');

CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_lang` (
  `id_loffc_block` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  PRIMARY KEY (`id_loffc_block`,`id_lang`)
) ENGINE=_MYSQL_ENGINE_ DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_loffc_block_lang` (`id_loffc_block`, `id_lang`, `title`) VALUES
 (1, 1, 'block 1 haha'),
(1, 2, 'block 1'),
(1, 3, 'block 1 span'),
(1, 4, 'block 1'),
(1, 5, 'block 1'),
(1, 6, 'block 1'),
(1, 7, 'block 1 haha'),
(46, 1, 'Servise'),
(46, 2, 'Servise'),
(46, 3, 'Servise'),
(46, 4, 'Servise'),
(46, 5, 'Servise'),
(46, 6, 'Servise'),
(46, 7, 'Servise'),
(54, 1, 'Information'),
(54, 2, 'My Account'),
(54, 3, 'My Account'),
(54, 4, 'My Account'),
(54, 5, 'My Account'),
(54, 6, 'My Account'),
(54, 7, 'Information'),
(55, 1, 'From Twitter'),
(55, 2, 'About Dropship'),
(55, 3, 'About Dropship'),
(55, 4, 'About Dropship'),
(55, 5, 'About Dropship'),
(55, 6, 'About Dropship'),
(55, 7, 'From Twitter'),
(56, 1, 'Payment Options'),
(56, 2, 'Payment Options'),
(56, 3, 'Payment Options'),
(56, 4, 'Payment Options'),
(56, 5, 'Payment Options'),
(56, 6, 'Payment Options'),
(56, 7, 'Payment Options'),
(57, 1, 'Block'),
(57, 2, 'Block'),
(57, 3, 'Block'),
(57, 4, 'Block'),
(57, 5, 'Block'),
(57, 6, 'Block'),
(57, 7, 'Block'),
(58, 1, 'block search'),
(58, 2, 'block search'),
(58, 3, 'block search'),
(58, 4, 'block search'),
(58, 5, 'block search'),
(58, 6, 'block search'),
(58, 7, 'block search');

";
?>